// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QDateEdit>
#include "XGlobal.h"

class XQT_EXPORT XDateEdit : public QDateEdit
{
    Q_OBJECT
public:
    using QDateEdit::QDateEdit;
    ~XDateEdit() override = default;

    XQT_WIDGET_COMMON(XDateEdit)
};
