// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QDoubleSpinBox>
#include "XGlobal.h"

class XQT_EXPORT XDoubleSpinBox : public QDoubleSpinBox
{
    Q_OBJECT
public:
    using QDoubleSpinBox::QDoubleSpinBox;
    ~XDoubleSpinBox() override = default;

    XQT_WIDGET_COMMON(XDoubleSpinBox)
};
