// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QKeySequenceEdit>
#include "XGlobal.h"

class XQT_EXPORT XKeySequenceEdit : public QKeySequenceEdit
{
    Q_OBJECT
public:
    using QKeySequenceEdit::QKeySequenceEdit;
    ~XKeySequenceEdit() override = default;

    XQT_WIDGET_COMMON(XKeySequenceEdit)
};
