// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QMdiSubWindow>
#include "XGlobal.h"

class XQT_EXPORT XMdiSubWindow : public QMdiSubWindow
{
    Q_OBJECT
public:
    using QMdiSubWindow::QMdiSubWindow;
    ~XMdiSubWindow() override = default;

    XQT_WIDGET_COMMON(XMdiSubWindow)
};
