// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QScrollArea>
#include "XGlobal.h"

class XQT_EXPORT XScrollArea : public QScrollArea
{
    Q_OBJECT
public:
    using QScrollArea::QScrollArea;
    ~XScrollArea() override = default;

    XQT_WIDGET_COMMON(XScrollArea)
};
