// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QSplitter>
#include "XGlobal.h"

class XQT_EXPORT XSplitter : public QSplitter
{
    Q_OBJECT
public:
    using QSplitter::QSplitter;
    ~XSplitter() override = default;

    XQT_WIDGET_COMMON(XSplitter)
};
