// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QToolButton>
#include "XGlobal.h"

class XQT_EXPORT XToolButton : public QToolButton
{
    Q_OBJECT
public:
    using QToolButton::QToolButton;
    ~XToolButton() override = default;

    XQT_WIDGET_COMMON(XToolButton)
};
