// Generated by tools/generate_widgets.py - do not edit by hand.
#pragma once

#include <QWizardPage>
#include "XGlobal.h"

class XQT_EXPORT XWizardPage : public QWizardPage
{
    Q_OBJECT
public:
    using QWizardPage::QWizardPage;
    ~XWizardPage() override = default;

    XQT_WIDGET_COMMON(XWizardPage)
};
