#!/usr/bin/env python3
"""
Generate the X* widget wrappers for xQt: one header and one source per class.

    include/XPushButton.h
    src/XPushButton.cpp
    include/xQt.h                umbrella header including every widget

Every concrete QWidget subclass of QtWidgets gets an X-prefixed subclass
(XPushButton : QPushButton, ...). Existing files are overwritten; a class
removed from the list below is deleted as well.

Run from anywhere:
    python tools/generate_widgets.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIR = ROOT / "include"
SRC_DIR = ROOT / "src"

# Abstract classes (QAbstract*) are not wrapped: X* classes derive from the
# concrete Qt class directly.
# Skipped on purpose: QSplitterHandle (created by QSplitter), QRhiWidget (RHI).
QT_WIDGETS = [
    # buttons
    "QPushButton", "QToolButton", "QCheckBox", "QRadioButton", "QCommandLinkButton",
    # inputs
    "QLineEdit", "QTextEdit", "QPlainTextEdit",
    "QSpinBox", "QDoubleSpinBox", "QDateEdit", "QTimeEdit", "QDateTimeEdit",
    "QComboBox", "QFontComboBox", "QKeySequenceEdit",
    "QSlider", "QDial", "QScrollBar", "QCalendarWidget",
    # display
    "QLabel", "QLCDNumber", "QProgressBar", "QTextBrowser", "QSplashScreen",
    # item views
    "QListView", "QListWidget", "QTableView", "QTableWidget",
    "QTreeView", "QTreeWidget", "QColumnView", "QHeaderView", "QUndoView",
    "QGraphicsView",
    # containers
    "QWidget", "QFrame", "QGroupBox", "QScrollArea", "QStackedWidget",
    "QTabWidget", "QTabBar", "QToolBox", "QSplitter", "QDockWidget",
    "QMdiArea", "QMdiSubWindow", "QFocusFrame", "QRubberBand", "QSizeGrip",
    # windows
    "QMainWindow", "QMenuBar", "QMenu", "QToolBar", "QStatusBar", "QDialogButtonBox",
    # dialogs
    "QDialog", "QMessageBox", "QFileDialog", "QColorDialog", "QFontDialog",
    "QInputDialog", "QProgressDialog", "QErrorMessage", "QWizard", "QWizardPage",
]

HEADER_TEMPLATE = """\
#pragma once

#include <{qname}>
#include "XGlobal.h"

class XQT_EXPORT {xname} : public {qname}
{{
    Q_OBJECT
public:
    using {qname}::{qname};
    ~{xname}() override = default;

    XQT_WIDGET_COMMON({xname})
}};
"""

SOURCE_TEMPLATE = """\
#include "{xname}.h"
"""

UMBRELLA_TEMPLATE = """\
// Generated by tools/generate_widgets.py - do not edit by hand.
// Umbrella header: includes every xQt widget.
#pragma once

#include "XGlobal.h"
{includes}
"""

GENERATED_MARK = "XQT_WIDGET_COMMON("


def x_name(qname: str) -> str:
    return "X" + qname[1:]


def remove_stale(expected_headers: set, expected_sources: set) -> int:
    """Delete generated wrapper files for classes no longer in QT_WIDGETS."""
    removed = 0
    for h in INCLUDE_DIR.glob("X*.h"):
        if h.name in expected_headers or h.name == "XGlobal.h":
            continue
        if GENERATED_MARK in h.read_text(encoding="utf-8", errors="ignore"):
            h.unlink()
            removed += 1
    for c in SRC_DIR.glob("X*.cpp"):
        if c.name in expected_sources or c.name == "XGlobal.cpp":
            continue
        text = c.read_text(encoding="utf-8", errors="ignore").strip()
        if text.startswith('#include "X') and text.count("\n") == 0:
            c.unlink()
            removed += 1
    return removed


def main() -> None:
    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    SRC_DIR.mkdir(parents=True, exist_ok=True)

    headers, sources = set(), set()
    for qname in QT_WIDGETS:
        xname = x_name(qname)
        headers.add(f"{xname}.h")
        sources.add(f"{xname}.cpp")
        (INCLUDE_DIR / f"{xname}.h").write_text(
            HEADER_TEMPLATE.format(xname=xname, qname=qname), encoding="utf-8", newline="\n")
        (SRC_DIR / f"{xname}.cpp").write_text(
            SOURCE_TEMPLATE.format(xname=xname), encoding="utf-8", newline="\n")

    includes = "\n".join(f'#include "{x_name(q)}.h"' for q in QT_WIDGETS)
    (INCLUDE_DIR / "xQt.h").write_text(
        UMBRELLA_TEMPLATE.format(includes=includes), encoding="utf-8", newline="\n")

    removed = remove_stale(headers, sources)
    print(f"generated {len(QT_WIDGETS)} classes ({len(QT_WIDGETS)} headers + {len(QT_WIDGETS)} sources), "
          f"removed {removed} stale files")


if __name__ == "__main__":
    main()
