#!/usr/bin/env python3
"""
Generate the X* widget wrappers for xQt: one header and one source per class.

    include/XPushButton.h
    src/XPushButton.cpp
    include/xQt.h                umbrella header including every widget

Every concrete QWidget subclass of QtWidgets gets an X-prefixed subclass
(XPushButton : QPushButton, ...). Generated files carry a marker comment on
their first line; only files with that marker are ever overwritten or deleted,
so hand-written classes (XTabBar, XTabWidget, ...) are safe.

Run from anywhere:
    python tools/generate_widgets.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIR = ROOT / "include"
SRC_DIR = ROOT / "src"

GENERATED_MARK = "// Generated by tools/generate_widgets.py - do not edit by hand."

# Hand-written classes: not generated, but included in the umbrella header.
HANDWRITTEN = ["XTabBar", "XTabWidget", "XToolTip", "XStyleManager", "XDebug"]

# Abstract classes (QAbstract*) are not wrapped: X* classes derive from the
# concrete Qt class directly.
# Skipped on purpose: QSplitterHandle (created by QSplitter), QRhiWidget (RHI).
# QTabBar / QTabWidget are hand-written (icon/text layout modes).
QT_WIDGETS = [
    # buttons
    "QPushButton", "QToolButton", "QCheckBox", "QRadioButton", "QCommandLinkButton",
    # inputs
    "QLineEdit", "QTextEdit", "QPlainTextEdit",
    "QSpinBox", "QDoubleSpinBox", "QDateEdit", "QTimeEdit", "QDateTimeEdit",
    "QComboBox", "QFontComboBox", "QKeySequenceEdit",
    "QSlider", "QDial", "QScrollBar", "QCalendarWidget",
    # display
    "QLabel", "QLCDNumber", "QProgressBar", "QTextBrowser", "QSplashScreen",
    # item views
    "QListView", "QListWidget", "QTableView", "QTableWidget",
    "QTreeView", "QTreeWidget", "QColumnView", "QHeaderView", "QUndoView",
    "QGraphicsView",
    # containers
    "QWidget", "QFrame", "QGroupBox", "QScrollArea", "QStackedWidget",
    "QToolBox", "QSplitter", "QDockWidget",
    "QMdiArea", "QMdiSubWindow", "QFocusFrame", "QRubberBand", "QSizeGrip",
    # windows
    "QMainWindow", "QMenuBar", "QMenu", "QToolBar", "QStatusBar", "QDialogButtonBox",
    # dialogs
    "QDialog", "QMessageBox", "QFileDialog", "QColorDialog", "QFontDialog",
    "QInputDialog", "QProgressDialog", "QErrorMessage", "QWizard", "QWizardPage",
]

HEADER_TEMPLATE = GENERATED_MARK + """
#pragma once

#include <{qname}>
#include "XGlobal.h"

class XQT_EXPORT {xname} : public {qname}
{{
    Q_OBJECT
public:
    using {qname}::{qname};
    ~{xname}() override = default;

    XQT_WIDGET_COMMON({xname})
}};
"""

SOURCE_TEMPLATE = GENERATED_MARK + """
#include "{xname}.h"
"""

UMBRELLA_TEMPLATE = GENERATED_MARK + """
// Umbrella header: includes every xQt widget.
#pragma once

#include "XGlobal.h"
{includes}
"""


def x_name(qname: str) -> str:
    return "X" + qname[1:]


def is_generated(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8", errors="ignore") as f:
            return f.readline().strip() == GENERATED_MARK
    except OSError:
        return False


def write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def remove_stale(expected: set) -> int:
    """Delete generated files for classes no longer in QT_WIDGETS."""
    removed = 0
    for path in list(INCLUDE_DIR.glob("X*.h")) + list(SRC_DIR.glob("X*.cpp")):
        if path.name in expected or not is_generated(path):
            continue
        path.unlink()
        removed += 1
    return removed


def main() -> None:
    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    SRC_DIR.mkdir(parents=True, exist_ok=True)

    expected = {"xQt.h"}          # umbrella header; glob is case-insensitive on Windows
    skipped = []
    for qname in QT_WIDGETS:
        xname = x_name(qname)
        header, source = INCLUDE_DIR / f"{xname}.h", SRC_DIR / f"{xname}.cpp"
        expected.update({header.name, source.name})
        # never overwrite a file somebody turned into hand-written code
        if header.exists() and not is_generated(header):
            skipped.append(header.name)
            continue
        write(header, HEADER_TEMPLATE.format(xname=xname, qname=qname))
        if not source.exists() or is_generated(source):
            write(source, SOURCE_TEMPLATE.format(xname=xname))

    includes = [f'#include "{x_name(q)}.h"' for q in QT_WIDGETS] + [f'#include "{h}.h"' for h in HANDWRITTEN]
    write(INCLUDE_DIR / "xQt.h", UMBRELLA_TEMPLATE.format(includes="\n".join(includes)))

    removed = remove_stale(expected)
    print(f"generated {len(QT_WIDGETS) - len(skipped)} classes, hand-written kept: {', '.join(HANDWRITTEN)}, "
          f"removed {removed} stale files"
          + (f", skipped (hand-written): {', '.join(skipped)}" if skipped else ""))


if __name__ == "__main__":
    main()
